### ISSUE TITLE
Add x-axis description to the export diagram

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/wardleymapstool#11]
Scott,

you've mentioned something about rendering svg instead of png files. Since the image rendering code is a mess, I would be happy to rewrite it. Would you recommend any library for svg rendering?

**Comment by ScottWeinstein** [comment]
personal favorite is [d3](http://d3js.org/), [snapsvg](http://snapsvg.io/) might be worth a look too. d3 will run on the server, which is nice for this use case.

**Comment by ScottWeinstein** [comment]
here's a start https://github.com/ScottWeinstein/wardleymapstool/compare/svg-client-11?expand=1

**Comment by cdaniel** [comment]
this is now done.
