### ISSUE TITLE
As a user I can save a copy of an existing map

### ISSUE THREAD

**Issue by ScottWeinstein** [cdaniel/wardleymapstool#14]

**Comment by cdaniel** [comment]
How should I read that? Do you want to download a map as svg (kind of ready), download as json (not ready) or tag particular version in the tool?

**Comment by ScottWeinstein** [comment]
As a UI feature. User is working on a map, say "self-driving-cars". They may want to play around w/ different versions of the map "self-driving-cars-patents", "self-driving-cars-openstandards", etc etc

**Comment by cdaniel** [comment]
This has been added yesterday.
