### ISSUE TITLE
Thumbnails and downloads not working

### ISSUE THREAD

**Issue by plegault3397** [cdaniel/wardleymapstool#268]
I ran into an issue and updated my wardleymapstool, I was able to get it up and running. Now the thumbnails and downloads are not available.

**Comment by cdaniel** [comment]
Any logs?

**Comment by plegault3397** [comment]
The Wardley Logs are empty

**Comment by plegault3397** [comment]
It was working for a long while and the certificate expired. I changed the certificate and then upgraded to the npm install wardleymaptool@1.0.3.

**Comment by cdaniel** [comment]
what system? I'll try to recreate this. Most probably an issue with dependencies.

**Comment by plegault3397** [comment]
Redhat
I was seeing these messages re-installing, I thought I saw the same before
 
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated phantom@0.7.2: v1 is no longer maintained, please upgrade to v2.0+ as soon possible.
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN engine escodegen@1.8.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

> contextify@0.1.15 install /app/node_modules/wardleymaptool/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

make: Entering directory `/app/node_modules/wardleymaptool/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  COPY Release/contextify.node
make: Leaving directory `/app/node_modules/wardleymaptool/node_modules/jsdom/node_modules/contextify/build'

> weak@1.0.1 install /app/node_modules/wardleymaptool/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

make: Entering directory `/app/node_modules/wardleymaptool/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
  SOLINK_MODULE(target) Release/obj.target/weakref.node
  COPY Release/weakref.node
make: Leaving directory `/app/node_modules/wardleymaptool/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by plegault3397** [comment]
I have the Docker version setup on another system and it works, however I'm not sure how to move the database from the nodejs version to the Docker version

**Comment by cdaniel** [comment]
RedHat as RHEL? or Fedora?

Is there any output on the console (it should be very chatty)?

You could try to change the serbver/config/mongodbdata.js on your docker and point out to the other database.

**Comment by plegault3397** [comment]
RHEL
[2016-09-06 10:58:40.705] [DEBUG] maps - finding related maps for map 5780e56ce9aa63897e44a33a
10.45.13.185 - - [Tue, 06 Sep 2016 14:58:41 GMT] "GET /map/5780e56ce9aa63897e44a33a HTTP/1.1" 200 15346 "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:58:41 GMT] "GET /api/map/5780e56ce9aa63897e44a33a/progressstate HTTP/1.1" 200 65 "https://awsacrnva1050.jnj.com:8443/map/5780e56ce9aa63897e44a33a" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:58:45.682] [DEBUG] exportmap - drawing svg 5780e56ce9aa63897e44a33a for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:58:45 GMT] "GET /api/svgforcedownload/5780e56ce9aa63897e44a33a/5780e56ce9aa63897e44a33a.svg HTTP/1.1" 200 69 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:07.680] [DEBUG] maps - getting maps for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:07 GMT] "GET / HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/map/5780e56ce9aa63897e44a33a" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.029] [DEBUG] exportmap - drawing thumbnail 5780e56ce9aa63897e44a33a for user root
[2016-09-06 10:59:08.031] [DEBUG] exportmap - drawing thumbnail 57348c9bfa9d628c7acfcac0 for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/5780e56ce9aa63897e44a33a HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/57348c9bfa9d628c7acfcac0 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.139] [DEBUG] exportmap - drawing thumbnail 55ba60e5d3be10f412e1d4bd for user root
[2016-09-06 10:59:08.140] [DEBUG] exportmap - drawing thumbnail 55b0ffffd92e0fe812e17d7a for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/55ba60e5d3be10f412e1d4bd HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/55b0ffffd92e0fe812e17d7a HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.267] [DEBUG] exportmap - drawing thumbnail 573a1f1764be4be76fc610ae for user root
[2016-09-06 10:59:08.268] [DEBUG] exportmap - drawing thumbnail 5780e868e9aa63897e44a33c for user root
[2016-09-06 10:59:08.268] [DEBUG] exportmap - drawing thumbnail 57727f0ce9aa63897e44a338 for user root
[2016-09-06 10:59:08.269] [DEBUG] exportmap - drawing thumbnail 57331b32fa9d628c7acfcabc for user root
[2016-09-06 10:59:08.270] [DEBUG] exportmap - drawing thumbnail 56c5caddd7359fc612a4879e for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/573a1f1764be4be76fc610ae HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/5780e868e9aa63897e44a33c HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/57727f0ce9aa63897e44a338 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/57331b32fa9d628c7acfcabc HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/56c5caddd7359fc612a4879e HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.509] [DEBUG] exportmap - drawing thumbnail 57360a48fa9d628c7acfcac4 for user root
[2016-09-06 10:59:08.510] [DEBUG] exportmap - drawing thumbnail 574ef47964be4be76fc610b4 for user root
[2016-09-06 10:59:08.511] [DEBUG] exportmap - drawing thumbnail 573e181c64be4be76fc610b0 for user root
[2016-09-06 10:59:08.511] [DEBUG] exportmap - drawing thumbnail 573354acfa9d628c7acfcabe for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/57360a48fa9d628c7acfcac4 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/574ef47964be4be76fc610b4 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/573e181c64be4be76fc610b0 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/573354acfa9d628c7acfcabe HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.831] [DEBUG] exportmap - drawing thumbnail 57cebe3b254a26e506014b0d for user root
[2016-09-06 10:59:08.832] [DEBUG] exportmap - drawing thumbnail 55b2334cd3be10f412e1d4b3 for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/57cebe3b254a26e506014b0d HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:08.870] [DEBUG] exportmap - drawing thumbnail 574dd4bf64be4be76fc610b2 for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:08 GMT] "GET /api/thumbnail/55b2334cd3be10f412e1d4b3 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:09 GMT] "GET /api/thumbnail/574dd4bf64be4be76fc610b2 HTTP/1.1" 304 - "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:10.625] [DEBUG] maps - getting map 55ba60e5d3be10f412e1d4bd for user root
[2016-09-06 10:59:10.627] [DEBUG] maps - finding related maps for map 55ba60e5d3be10f412e1d4bd
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:10 GMT] "GET /map/55ba60e5d3be10f412e1d4bd HTTP/1.1" 200 20926 "https://awsacrnva1050.jnj.com:8443/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:11 GMT] "GET /api/map/55ba60e5d3be10f412e1d4bd/progressstate HTTP/1.1" 200 65 "https://awsacrnva1050.jnj.com:8443/map/55ba60e5d3be10f412e1d4bd" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[2016-09-06 10:59:14.798] [DEBUG] exportmap - drawing svg 55ba60e5d3be10f412e1d4bd for user root
10.45.13.185 - - [Tue, 06 Sep 2016 14:59:14 GMT] "GET /api/svgforcedownload/55ba60e5d3be10f412e1d4bd/55ba60e5d3be10f412e1d4bd.svg HTTP/1.1" 200 69 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"



![phil testing](https://cloud.githubusercontent.com/assets/7073595/18278715/16fe47da-7421-11e6-964d-c3fd4b9cee78.png)

**Comment by plegault3397** [comment]
Database is on a different server

**Comment by cdaniel** [comment]
I can confirm that installing via npm does not work.

Please backup the database now.

I have just published the 1.1.0 version, could you try it out (export as png may still not work, but at least svg should work)?

**Comment by cdaniel** [comment]
BTW. I am working on a totally new version of the tool (see https://github.com/cdaniel/atlas2 / http://atlas2.wardleymaps.com/).

**Comment by plegault3397** [comment]
Yes 1.1.0 is working
Thanks for the quick response 
I will check out the new tool
